# Generated by Django 4.2.7 on 2025-06-01 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('slug', models.SlugField(unique=True, verbose_name='슬러그')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='기술명')),
                ('color', models.CharField(default='#000000', max_length=7, verbose_name='색상')),
            ],
            options={
                'verbose_name': '기술',
                'verbose_name_plural': '기술',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='강의명')),
                ('description', models.TextField(verbose_name='강의 설명')),
                ('thumbnail', models.ImageField(blank=True, upload_to='course_thumbnails/', verbose_name='썸네일')),
                ('level', models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '고급')], max_length=20, verbose_name='난이도')),
                ('price_type', models.CharField(choices=[('free', '무료'), ('paid', '유료')], max_length=10, verbose_name='가격 유형')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='가격')),
                ('is_bestseller', models.BooleanField(default=False, verbose_name='베스트셀러')),
                ('is_updated', models.BooleanField(default=False, verbose_name='최신 업데이트')),
                ('is_discount', models.BooleanField(default=False, verbose_name='할인')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.category', verbose_name='카테고리')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='강사')),
                ('technologies', models.ManyToManyField(to='courses.technology', verbose_name='기술 스택')),
            ],
            options={
                'verbose_name': '강의',
                'verbose_name_plural': '강의',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='평점')),
                ('comment', models.TextField(verbose_name='리뷰 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.course', verbose_name='강의')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰',
                'unique_together': {('course', 'user')},
            },
        ),
    ]
