# Generated by Django 4.2.7 on 2025-06-01 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='챕터명')),
                ('description', models.TextField(blank=True, verbose_name='챕터 설명')),
                ('order', models.PositiveIntegerField(verbose_name='순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='courses.course', verbose_name='강의')),
            ],
            options={
                'verbose_name': '챕터',
                'verbose_name_plural': '챕터',
                'ordering': ['course', 'order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='레슨명')),
                ('description', models.TextField(blank=True, verbose_name='레슨 설명')),
                ('duration', models.CharField(blank=True, max_length=20, verbose_name='재생시간')),
                ('order', models.PositiveIntegerField(verbose_name='순서')),
                ('is_preview', models.BooleanField(default=False, verbose_name='미리보기 가능')),
                ('video_url', models.URLField(blank=True, verbose_name='비디오 URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.chapter', verbose_name='챕터')),
            ],
            options={
                'verbose_name': '레슨',
                'verbose_name_plural': '레슨',
                'ordering': ['chapter', 'order'],
                'unique_together': {('chapter', 'order')},
            },
        ),
    ]
