# Generated by Django 4.2.7 on 2025-06-02 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_chapter_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='할인가격'),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, max_length=20, verbose_name='재생시간'),
        ),
        migrations.AddField(
            model_name='course',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='유튜브 영상 URL을 입력하세요', verbose_name='유튜브 URL'),
        ),
        migrations.AddField(
            model_name='course',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='유튜브 비디오 ID'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_key', models.CharField(max_length=200, unique=True, verbose_name='결제 키')),
                ('order_id', models.CharField(max_length=100, unique=True, verbose_name='주문 ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='결제 금액')),
                ('status', models.CharField(choices=[('pending', '결제 대기'), ('success', '결제 완료'), ('failed', '결제 실패'), ('cancelled', '결제 취소'), ('refunded', '환불 완료')], default='pending', max_length=20, verbose_name='결제 상태')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='결제 수단')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='승인 시간')),
                ('failed_reason', models.TextField(blank=True, verbose_name='실패 사유')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='강의')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '결제',
                'verbose_name_plural': '결제',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, verbose_name='구매일시')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='강의')),
                ('payment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.payment', verbose_name='결제 정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '구매',
                'verbose_name_plural': '구매',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
