# Generated by Django 4.2.7 on 2025-06-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_discount_price_course_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_description',
            field=models.TextField(blank=True, help_text='이 영상에서 다루는 내용을 자세히 설명해주세요', verbose_name='영상 설명'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='유튜브 영상 URL을 입력하세요', verbose_name='유튜브 URL'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=20, verbose_name='유튜브 비디오 ID'),
        ),
    ]
